/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementapp;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author admin
 */
public class CheckAvailable extends javax.swing.JFrame {

    /**
     * Creates new form CheckAvailableForm
     * @param mainForm
     */
    public CheckAvailable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEnterInfo = new javax.swing.JPanel();
        jLabelRoomType = new javax.swing.JLabel();
        jComboBoxRoomType = new javax.swing.JComboBox<>();
        jDateChooserArrival = new com.toedter.calendar.JDateChooser();
        jLabelDepartureDate = new javax.swing.JLabel();
        jDateChooserDeparture = new com.toedter.calendar.JDateChooser();
        jLabelArrivalDate = new javax.swing.JLabel();
        jButtonShowRoomType = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jPanelSearchTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSearchResult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelEnterInfo.setPreferredSize(new java.awt.Dimension(400, 189));

        jLabelRoomType.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabelRoomType.setText("Loại phòng");

        jComboBoxRoomType.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        jLabelDepartureDate.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabelDepartureDate.setText("Ngày đi");

        jLabelArrivalDate.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabelArrivalDate.setText("Ngày đến");

        jButtonShowRoomType.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButtonShowRoomType.setText("Hiển thị");
        jButtonShowRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowRoomTypeActionPerformed(evt);
            }
        });

        jButtonSearch.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButtonSearch.setText("Tìm kiếm");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEnterInfoLayout = new javax.swing.GroupLayout(jPanelEnterInfo);
        jPanelEnterInfo.setLayout(jPanelEnterInfoLayout);
        jPanelEnterInfoLayout.setHorizontalGroup(
            jPanelEnterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnterInfoLayout.createSequentialGroup()
                        .addGroup(jPanelEnterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelRoomType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelArrivalDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDepartureDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEnterInfoLayout.createSequentialGroup()
                                .addComponent(jComboBoxRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonShowRoomType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jDateChooserDeparture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserArrival, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEnterInfoLayout.setVerticalGroup(
            jPanelEnterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelArrivalDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanelEnterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDepartureDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRoomType)
                    .addComponent(jComboBoxRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonShowRoomType))
                .addGap(13, 13, 13)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTableSearchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSearchResult);

        javax.swing.GroupLayout jPanelSearchTableLayout = new javax.swing.GroupLayout(jPanelSearchTable);
        jPanelSearchTable.setLayout(jPanelSearchTableLayout);
        jPanelSearchTableLayout.setHorizontalGroup(
            jPanelSearchTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSearchTableLayout.setVerticalGroup(
            jPanelSearchTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jPanelSearchTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelEnterInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanelEnterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelSearchTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private RoomType rt = new RoomType();
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        new MainForm().setVisible(true);
        rt.dispose();
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jButtonShowRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowRoomTypeActionPerformed
        rt.setVisible(true);
        rt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        rt.setLocation(utils.getScreenSize().width - rt.getSize().width,
                utils.getScreenSize().height/2 - rt.getSize().height/2);
    }//GEN-LAST:event_jButtonShowRoomTypeActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        if (jDateChooserArrival.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập ngày đến. "
                    + "Mời bạn chọn ngày đến để tìm kiếm phòng trống.", "Lỗi", 0);
        }
        else if (jDateChooserDeparture.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập ngày đi. "
                    + "Mời bạn chọn ngày đi để tìm kiếm phòng trống.", "Lỗi", 0);
        }
        else if (jDateChooserDeparture.getDate().compareTo(jDateChooserDeparture.getDate()) < 0) {
            JOptionPane.showMessageDialog(null, "Ngày bạn đi không thể sau ngày bạn đến. "
                    + "Mời bạn chọn lại ngày đi phù hợp.", "Lỗi", 0);
        }
        else if (jDateChooserArrival.getDate().compareTo(java.sql.Date.valueOf(java.time.LocalDate.now())) < 0) {
            JOptionPane.showMessageDialog(null, "Ngày bạn đến không thể trước ngày hôm nay được. "
                    + "Mời bạn chọn lại ngày đến phù hợp.", "Lỗi", 0);
        }
        else {
            Date checkInDate = jDateChooserArrival.getDate();
            Date checkOutDate = jDateChooserDeparture.getDate();
            String format = utils.getMySQLDateFormat();
            String checkInDateString = utils.convertJavaUtilDateToString(checkInDate, format);
            String checkOutDateString = utils.convertJavaUtilDateToString(checkOutDate, format);
            String roomType = jComboBoxRoomType.getSelectedItem().toString();
            String[] inputString = { 
                checkInDateString,
                checkInDateString,
                checkOutDateString,
                checkOutDateString,
                checkInDateString,
                checkOutDateString,
                roomType
            };
            
            try {
                String prepareQuery = "SELECT * "
                                    + "FROM "
                                    + utils.getDBName()
                                    + ".room_details "
                                    + "WHERE room_no NOT IN "
                                    + "("
                                    +    "SELECT room_no "
                                    +    "FROM "
                                    +    utils.getDBName() + ".tbl_reserve "
                                    +    "where (? < departure_date and ? >= arrival_date) "
                                    +    "or (? > arrival_date and ? <= departure_date) "
                                    +    "or (? <= arrival_date and ? >= departure_date)"
                                    + ") and room_type = ?;";
                ResultSet rs = utils.executeQueryWithPreparedStatement(prepareQuery, inputString);
                
                String[] tb_columns = { "Số phòng", "Loại phòng", "Số lượng giường ngủ", "Giá" };
                String[] db_columns = { "room_no", "room_type", "no_bed", "price" };
                utils.tableRender(jTableSearchResult, tb_columns, db_columns, rs);
            } catch (SQLException ex) {
                Logger.getLogger(CheckAvailable.class.getName()).log(Level.SEVERE, null, ex);
            }
            jPanelSearchTable.setVisible(true);
            this.pack();
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ResultSet rs = utils.executeQuery("select type_id from 8gQHxi21p3.room_type");
        try {
            while(rs.next()){
                jComboBoxRoomType.addItem(rs.getString("type_id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CheckAvailable.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPanelSearchTable.setVisible(false);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
//        this.setSize(jPanelEnterInfo.getSize());
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonShowRoomType;
    private javax.swing.JComboBox<String> jComboBoxRoomType;
    private com.toedter.calendar.JDateChooser jDateChooserArrival;
    private com.toedter.calendar.JDateChooser jDateChooserDeparture;
    private javax.swing.JLabel jLabelArrivalDate;
    private javax.swing.JLabel jLabelDepartureDate;
    private javax.swing.JLabel jLabelRoomType;
    private javax.swing.JPanel jPanelEnterInfo;
    private javax.swing.JPanel jPanelSearchTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSearchResult;
    // End of variables declaration//GEN-END:variables
}
