/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementapp;

import java.sql.Connection;
import javax.swing.JFrame;

/**
 *
 * @author DinhTam
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public MainForm() {
        initComponents();
        jLabelUsername.setText(utils.getUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMakeReservation = new javax.swing.JButton();
        jButtonRoomManagement = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jButtonCheckAvaialable = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jButtonAddCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonMakeReservation.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButtonMakeReservation.setText("Yêu cầu đặt phòng");
        jButtonMakeReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeReservationActionPerformed(evt);
            }
        });

        jButtonRoomManagement.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButtonRoomManagement.setText("Quản lý phòng");
        jButtonRoomManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoomManagementActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Tên người dùng:");

        jLabelUsername.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabelUsername.setText("jLabel2");

        jButtonCheckAvaialable.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButtonCheckAvaialable.setText("Tìm phòng trống");
        jButtonCheckAvaialable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckAvaialableActionPerformed(evt);
            }
        });

        jButtonLogOut.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButtonLogOut.setText("Đăng xuất");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });

        jButtonAddCustomer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonAddCustomer.setText("Quản lý khách hàng");
        jButtonAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonCheckAvaialable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUsername)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLogOut))
                    .addComponent(jButtonAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRoomManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMakeReservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUsername)
                    .addComponent(jButtonLogOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonRoomManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonMakeReservation)
                .addGap(0, 0, 0)
                .addComponent(jButtonCheckAvaialable, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAddCustomer, jButtonCheckAvaialable, jButtonMakeReservation, jButtonRoomManagement});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonMakeReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeReservationActionPerformed
        new MakeReservation().setVisible(true);
    }//GEN-LAST:event_jButtonMakeReservationActionPerformed

    private void jButtonRoomManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoomManagementActionPerformed
        // TODO add your handling code here:
        RoomManagement f = new RoomManagement();
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonRoomManagementActionPerformed

    private void jButtonCheckAvaialableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckAvaialableActionPerformed
        CheckAvailable checkform = new CheckAvailable();
        checkform.setVisible(true);
        checkform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCheckAvaialableActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        new Login().setVisible(true);
        utils.setUsername("");
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCustomerActionPerformed
        // TODO add your handling code here:
        CustomerManagement r = new CustomerManagement();
        r.setLocationRelativeTo(null);
        r.setVisible(true);
        r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonAddCustomerActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCustomer;
    private javax.swing.JButton jButtonCheckAvaialable;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonMakeReservation;
    private javax.swing.JButton jButtonRoomManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUsername;
    // End of variables declaration//GEN-END:variables
}
