/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author admin
 */
public class RoomManagement extends javax.swing.JFrame {

    /**
     * Creates new form RoomManagement
     * @param connGlobal
     * @param db_name
     */
    public RoomManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldRoomNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRoomType = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldRoomPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRoomDetails = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNoBed = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Mã phòng");

        jTextFieldRoomNo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setText("Loại phòng");

        jLabel4.setText("Giá");

        jTableRoomDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Loại phòng", "Tình trạng phòng", "Giá phòng"
            }
        ));
        jTableRoomDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableRoomDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRoomDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRoomDetails);

        jButtonAdd.setText("Thêm");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Sửa");
        jButtonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Xoá");
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel5.setText("Số lượng giường");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setText("THÔNG TIN PHÒNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldNoBed, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldRoomNo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldRoomType, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldRoomPrice, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNoBed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit)
                            .addComponent(jButtonDelete))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAdd, jButtonDelete, jButtonEdit});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void defaultView() {
        jTextFieldRoomNo.setText("");
        jTextFieldRoomType.setText("");
        jTextFieldNoBed.setText("");
        jTextFieldRoomPrice.setText("");
        
        jButtonAdd.setEnabled(true);
        jButtonEdit.setEnabled(false);
        jButtonDelete.setEnabled(false);
        
        jTextFieldRoomNo.setEditable(true);
        jTableRoomDetails.clearSelection();
    }
    
    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        int rowIdx = jTableRoomDetails.getSelectedRow();
        String updateQuery = "UPDATE  "
                + utils.getDBName()
                +".`room_details` SET "
                + "`room_type` = ?, "
                + "`no_bed` = ?, "
                + "`price` = ? "
                + "WHERE (`room_no` = ?);";
        String[] data = { jTextFieldRoomType.getText(), jTextFieldNoBed.getText(), jTextFieldRoomPrice.getText(), jTextFieldRoomNo.getText() };
        utils.updateQueryWithPreparedStatment(updateQuery, data);
        JOptionPane.showMessageDialog(null, "Sửa thông tin phòng thành công", "Thông báo", 1);
        
        jTableRoomDetails.setValueAt(jTextFieldRoomNo.getText(), rowIdx, 0);
        jTableRoomDetails.setValueAt(jTextFieldRoomType.getText(), rowIdx, 1);
        jTableRoomDetails.setValueAt(jTextFieldNoBed.getText(), rowIdx, 2);
        jTableRoomDetails.setValueAt(jTextFieldRoomPrice.getText(), rowIdx, 3);
        
        defaultView();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int rowIndex = jTableRoomDetails.getSelectedRow();
        String room_no = (String) jTableRoomDetails.getValueAt(rowIndex, 0);
        // For Debuging only
        String[] data = { room_no };
        String delQuery = "DELETE FROM "
                + utils.getDBName()
                +".`room_details` WHERE (`room_no` = ?)";
       
        utils.updateQueryWithPreparedStatment(delQuery, data);
        JOptionPane.showMessageDialog(null, "Xoá phòng thành công", "Thông báo", 1);
        DefaultTableModel tm = (DefaultTableModel) jTableRoomDetails.getModel();
        tm.removeRow(rowIndex);
        
        defaultView();
    }//GEN-LAST:event_jButtonDeleteActionPerformed
    
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        String idroom = jTextFieldRoomNo.getText();
        String type = jTextFieldRoomType.getText();
        String no_bed = jTextFieldNoBed.getText();
        String price = jTextFieldRoomPrice.getText();
        String[] data = { idroom, type, no_bed, price };
        
        DefaultTableModel tm = (DefaultTableModel) jTableRoomDetails.getModel();
        tm.addRow(data);
        
        String addQuery = "INSERT INTO "
                + utils.getDBName() +
                ".`room_details` (`room_no`, `room_type`, `no_bed`, `price`)"
                + " VALUES (?, ?, ?, ?)";
        utils.updateQueryWithPreparedStatment(addQuery, data);
        JOptionPane.showMessageDialog(null, "Thêm phòng mới thành công", "Thông báo", 1);
        
        defaultView();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTableRoomDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRoomDetailsMouseClicked
        // TODO add your handling code here:
        jButtonEdit.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonAdd.setEnabled(false);
        jTextFieldRoomNo.setEditable(false);
        
        int rowIndex = jTableRoomDetails.getSelectedRow();
        String idroom = (String) jTableRoomDetails.getValueAt(rowIndex, 0);
        String roomType = (String) jTableRoomDetails.getValueAt(rowIndex, 1);
        String no_bed = (String) jTableRoomDetails.getValueAt(rowIndex, 2);
        String roomPrice = (String) jTableRoomDetails.getValueAt(rowIndex, 3);
        
        jTextFieldRoomNo.setText(idroom);
        jTextFieldRoomType.setText(roomType);
        jTextFieldNoBed.setText(no_bed);
        jTextFieldRoomPrice.setText(roomPrice);
    }//GEN-LAST:event_jTableRoomDetailsMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jButtonDelete.setEnabled(false);
        jButtonEdit.setEnabled(false);
        jButtonAdd.setEnabled(true);
        ResultSet rs = utils.executeQuery("SELECT * from " + utils.getDBName() + ".room_details;");
        String[] tb_columns = { "Mã phòng", "Loại Phòng", "Số lượng giường", "Giá" };
        String[] db_columns = { "room_no", "room_type", "no_bed", "price" };
        utils.tableRender(jTableRoomDetails, tb_columns, db_columns, rs);
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRoomDetails;
    private javax.swing.JTextField jTextFieldNoBed;
    private javax.swing.JTextField jTextFieldRoomNo;
    private javax.swing.JTextField jTextFieldRoomPrice;
    private javax.swing.JTextField jTextFieldRoomType;
    // End of variables declaration//GEN-END:variables
}
